# docker-compose for develop

version: '3.3'

volumes:
  postgres_data: {}

services:
  backend:
    build:
      context: ./backend
    depends_on:
      - postgres
#      - redis
    volumes:
      - ./backend:/app
    command: /start.sh
    entrypoint: /entrypoint.sh
    restart: always
    env_file: .env
    ports:
      - "${CUSTOM_PORT}:8000"
  
  postgres:
    image: postgres:12.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env


#  redis:
#    image: library/redis:5.0-alpine
#    restart: unless-stopped
#
#
#  celery_worker:
#    build:
#      context: ./backend
#    command: celery -A project worker -l info
#    env_file: .env
#    volumes:
#      - ./backend:/app
#    restart: unless-stopped
#    depends_on:
#      - backend
#      - redis
#
#
#  celery_beat:
#    build:
#      context: ./backend
#    command: celery -A project beat -l info
#    env_file: .env
#    volumes:
#      - ./backend:/app
#    restart: unless-stopped
#    depends_on:
#      - backend
#      - redis